# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=true
org.gradle.java.home=C:/Users/allew/.jdks/temurin-25.0.3

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
version=1.0.0-26.1
group=atom.variants

# Dependencies
fabric_api_version=0.145.1+26.1

curseforge_id=1719783
modrinth_id=20l7DL7J
